# Generated by Django 4.0 on 2024-04-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_category_club_verification_member_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='image',
            new_name='banner',
        ),
    ]
