# Generated by Django 4.0 on 2024-04-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
