# Generated by Django 4.0 on 2024-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member')], max_length=250),
        ),
    ]
